---

- hosts: log*

- hosts: log.server*
  vars:
    - fluentd:
        matches:
          - [1, 'reformer', {}]
          - [10, 'debug', {}]
          - [99, 'archive', {'log_dir': '/tmp'}]
        sources:
          - [20, 'forwarding', {}]
  roles:
    - base
    - ntp
    - { role: fluentd, tags: [ server ] }

- hosts: log.client*
  vars:
    - fluentd:
        matches:
#          - [10, 'debug', {}]
          - [99, 'forwarding', {}]
        sources:
          - [20, 'socket', {}]
        in_tail:
          files:
            - {'name': 'balanced.log', 'path': '/var/log/balanced.log', 'format': 'json'}
            - {'name': 'td-agent.log', 'path': '/var/log/td-agent/td-agent.log', 'format': '/^(?<line>.*)$/', 'tag': 'debug.td_agent_client'}
            - {'name': 'balanced.nginx.access', 'path': '/var/log/nginx/access.log', 'format': 'balanced-nginx-access', tag: 'debug.nginx.access'}
            - {'name': 'balanced.nginx.error', 'path': '/var/log/nginx/error.log', 'format': 'nginx-error', tag: 'debug.nginx.error'}
        in_forward:
          servers:
            - 10.20.2.11
            - 10.20.2.12
            - 10.20.2.13  # does not actually exist, simulates a down host
  roles:
    - base
    - ntp
    - { role: fluentd, tags: [ client ] }
