---

- hosts: log.server*
  vars:
    fluentd_sources:
      - priority: 20
        name: forwarding
        options: {}
    fluentd_matches:
      - priority: 05
        name: reformer
        options: {}
      - priority: 10
        name: debug
        options:
          pattern: 'debug.**'
    fluentd_services:
      - name: balanced
        pattern: 'balanced.**'
        stores:
          s3:
            s3_prefix: balanced-dev
          file:
            path: balanced-dev
      - name: justitia
        pattern: 'justitia.**'
        stores:
          s3:
            s3_prefix: justitia-dev
          file:
            path: justitia-dev
    fluentd_plugins:
      - fluent-plugin-record-reformer
      - fluent-plugin-kafka
  roles:
    - base
    - ntp
    - td-agent
    - fluentd

- hosts: log.client*
  vars:
    fluentd_matches:
      - priority: 99
        name: forwarding
        options:
          servers: [10.20.2.11, 10.20.2.12, 10.20.2.13]
    fluentd_in_tail_files:
      - name: balanced.log
        path: /var/log/balanced.log
        format: json
  tasks:
   - file: path=/var/log/balanced.log state=touch
     sudo: yes
  roles:
    - base
    - ntp
    - td-agent
    - fluentd
